In [1]:
from fastai import *
from fastai.text import *
import bert_model
import numpy as np 

I1114 06:58:55.383507 139828601800512 file_utils.py:39] PyTorch version 1.1.0 available.
I1114 06:58:55.424413 139828601800512 modeling_xlnet.py:194] Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .
I1114 06:58:55.432470 139828601800512 modeling.py:230] Better speed can be achieved with apex installed from https://www.github.com/nvidia/apex .


In [2]:
bert = bert_model.load_bert_model('.')

I1114 06:59:36.286322 139828601800512 modeling.py:580] loading archive file https://s3.amazonaws.com/models.huggingface.co/bert/bert-base-uncased.tar.gz from cache at /home/superceed1/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba
I1114 06:59:36.288807 139828601800512 modeling.py:588] extracting archive file /home/superceed1/.pytorch_pretrained_bert/9c41111e2de84547a463fd39217199738d1e3deb72d4fec4399e6e241983c6f0.ae3cef932725ca7a30cdcb93fc6e09150a55e2a130ec7af63975a16c153ae2ba to temp dir /tmp/tmps8yabccx
I1114 06:59:42.496191 139828601800512 modeling.py:598] Model config {
  "attention_probs_dropout_prob": 0.1,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "type_vocab_size": 2,
  "vocab_size": 30522
}


In [3]:
bert.load('head-3')

Learner(data=TextClasDataBunch;

Train: LabelList (127656 items)
x: TextList
[CLS] grandma terri should burn in trash grandma terri is trash i hate grandma terri fk her to hell [SEP],[CLS] may utc it would be easiest if you were to admit to being a member of the involved portuguese lodge and then there would be no requirement to acknowledge whether you had a previous account carlos bot ##el ##ho did not have a good record or not and i would then remove the sock ##pu ##ppet template as irrelevant w ##pc ##oi permit is people to edit those articles such as ms ##ja ##pan does but just means you have to be more careful in ensuring that references back your edit is and that np ##ov is upheld [SEP],[CLS] the object ##ivity of this discussion is doubtful none ##xi ##sten ##t as indicated earlier the section on marxist leaders views is misleading a it lays un ##war ##rant ##ed and excessive emphasis on tr ##ots ##ky creating the misleading impression that other prominent marxist ##s marx eng #

In [4]:
text = 'you are so sweet'
bert.predict(text)

(MultiCategory ,
 tensor([0., 0., 0., 0., 0., 0.]),
 tensor([4.0619e-02, 2.0407e-05, 2.1858e-03, 4.0995e-04, 3.2507e-03, 1.0345e-03]))

In [5]:
text = 'you are pathetic piece of shit'
result = bert.predict(text)

In [8]:
bert.validate()

[0.043986607, tensor(0.9807)]

In [10]:
bert.get_preds()

[tensor([[5.6693e-04, 2.5819e-05, 6.7672e-05, 2.6106e-05, 9.2746e-05, 4.1498e-05],
         [5.2298e-04, 3.0124e-05, 6.4323e-05, 2.8786e-05, 9.3707e-05, 4.4073e-05],
         [4.5596e-04, 4.0818e-05, 5.9363e-05, 3.5280e-05, 9.7039e-05, 5.0652e-05],
         ...,
         [5.6003e-04, 2.6394e-05, 6.7182e-05, 2.6463e-05, 9.2870e-05, 4.1835e-05],
         [6.3144e-04, 2.1654e-05, 7.2082e-05, 2.3548e-05, 9.2366e-05, 3.9185e-05],
         [4.8418e-03, 1.0551e-05, 2.6650e-04, 4.8724e-05, 2.7955e-04, 1.0864e-04]]),
 tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]])]

In [11]:
bert.show_results()

In [12]:
preds = bert.pred_batch()

In [13]:
preds[:10]

tensor([[5.6693e-04, 2.5819e-05, 6.7672e-05, 2.6106e-05, 9.2746e-05, 4.1498e-05],
        [5.2298e-04, 3.0124e-05, 6.4323e-05, 2.8786e-05, 9.3707e-05, 4.4073e-05],
        [4.5596e-04, 4.0818e-05, 5.9363e-05, 3.5280e-05, 9.7039e-05, 5.0652e-05],
        [4.7330e-04, 3.7391e-05, 6.0560e-05, 3.3231e-05, 9.5877e-05, 4.8539e-05],
        [4.7872e-04, 3.6436e-05, 6.0949e-05, 3.2659e-05, 9.5576e-05, 4.7952e-05],
        [4.6359e-04, 3.9224e-05, 5.9886e-05, 3.4317e-05, 9.6471e-05, 4.9663e-05],
        [1.1613e-01, 5.2986e-05, 7.0334e-03, 1.2046e-03, 1.1638e-02, 2.8328e-03],
        [8.4817e-04, 1.5383e-05, 8.6428e-05, 2.0202e-05, 9.6748e-05, 3.7431e-05],
        [5.7027e-04, 2.5551e-05, 6.7912e-05, 2.5940e-05, 9.2699e-05, 4.1342e-05],
        [5.0186e-04, 3.2831e-05, 6.2683e-05, 3.0461e-05, 9.4470e-05, 4.5729e-05]])

# Predict test set

In [20]:
import pandas as pd

In [52]:
label_columns = ["toxic", "severe_toxic", "obscene", "threat", "insult", "identity_hate", "category"]

In [21]:
test_df = pd.read_csv('../data/toxic_comment/cleaned/test.csv')

In [34]:
batch_pred = bert.get_preds(list(test_df['comment_text'].values))

In [37]:
batch_pred

[tensor([[4.7520e-04, 3.7057e-05, 6.0700e-05, 3.3038e-05, 9.5794e-05, 4.8338e-05],
         [4.8894e-04, 3.4752e-05, 6.1703e-05, 3.1639e-05, 9.5052e-05, 4.6914e-05],
         [4.9875e-04, 3.3275e-05, 6.2438e-05, 3.0734e-05, 9.4591e-05, 4.6002e-05],
         ...,
         [3.8317e-03, 1.0634e-05, 2.2873e-04, 4.0591e-05, 2.2862e-04, 8.9445e-05],
         [1.6366e-03, 1.1263e-05, 1.3264e-04, 2.2775e-05, 1.2899e-04, 4.8231e-05],
         [6.0834e-04, 2.2929e-05, 7.0527e-05, 2.4324e-05, 9.2362e-05, 3.9859e-05]]),
 tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         ...,
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]])]

In [38]:
test_values = list(test_df['comment_text'].values)

In [40]:
results = bert.predict(test_values[0])

In [73]:
submission_df = pd.DataFrame([], columns=label_columns)

In [74]:
to_write_values = []
for value in test_values[:10]:
    result = bert.predict(value)
    percentage = result[2]
    predicted_category = result[0]
    
    to_write = percentage.tolist()
    to_write.append(predicted_category)
    submission_df.loc[-1] = to_write
    submission_df.index = submission_df.index + 1  # shifting index
    submission_df = submission_df.sort_index() 
#     break
submission_df

toxic  severe_toxic   obscene    threat    insult  identity_hate  \
0  0.000451      0.000042  0.000059  0.000036  0.000097       0.000051   
1  0.001625      0.000011  0.000132  0.000023  0.000129       0.000048   
2  0.430046      0.000578  0.043833  0.006330  0.076600       0.013767   
3  0.000724      0.000018  0.000078  0.000021  0.000093       0.000038   
4  0.000465      0.000039  0.000060  0.000034  0.000096       0.000050   
5  0.001323      0.000012  0.000116  0.000021  0.000115       0.000043   
6  0.000456      0.000041  0.000059  0.000035  0.000097       0.000051   
7  0.001007      0.000014  0.000097  0.000020  0.000102       0.000039   
8  0.000447      0.000043  0.000059  0.000037  0.000098       0.000052   
9  0.998115      0.394998  0.991098  0.034199  0.932204       0.171291   

               category  
0                        
1                        
2                        
3                        
4                        
5                        
6                        
7                        
8                        
9  toxic;obscene;insult

In [77]:
Submit = test_df[['id', 'comment_text']].copy()
Submit = Submit[:10]
Submit = pd.concat([Submit,submission_df],axis=1)
Submit.to_csv("../output/bert.csv",index=False)